name: ContributorCount
on:
  schedule: [{cron: "30 1 * * *"}]
  workflow_dispatch:
jobs:
  contributors-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download File
        run: |
          sudo apt-get install ripgrep
          curl -I -s -o /dev/null -w '%header{link}' "https://api.github.com/repos/ublue-os/bazzite/contributors?per_page=1&anon=true" | rg 'page=(\d+)>; rel="last"' -or '$1' > contributors.txt
        working-directory: ${{ github.workspace }}

      - name: Write contributors.txt to Repostiory
        uses: test-room-7/action-update-file@v2
        with:
            file-path: contributors.txt
            commit-msg: Contributor Count Update
            github-token: ${{ secrets.GITHUB_TOKEN }}
